name: "CI-CD-Workflow"

on:
  # push:
  #   branches:
  #     - main

  workflow_dispatch:
    inputs:
      EnvFile:
        description: 'Environment Variables file:'
        default: env-config-var.txt
        required: true

    ### USAGE: ${{ github.event.inputs.EnvFile }} ###
        
env:
  ENV_FILE: ${{ github.event.inputs.EnvFile }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@master

    - name: Import environment configuration variables maps file
      id: import-env
      shell: bash
      run: |
        while read line; do
          echo "$line" >> $GITHUB_ENV
        done < ${{ env.ENV_FILE }}
    
    - uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: "Build and push to container registry"
      run: |
        docker build . -t ${{ secrets.ACR_URL }}/${{env.IMAGE_NAME}}:${{ github.sha }}
        docker push ${{ secrets.ACR_URL }}/${{env.IMAGE_NAME}}:${{ github.sha }}

  CD:
    needs: [build]
    uses: mehmetca-tr/CI-CD-workflows/.github/workflows/cd-workflow.yml@main
    with:
      ENV_FILE: ${{ github.event.inputs.EnvFile }}
    secrets:
      ACR_URL: ${{ secrets.ACR_URL }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
