name: "Test-CD-Workflow"

on:
  # push:
  #  branches:
  #    - main

  workflow_dispatch:  

env:
  CLUSTER_NAME: contoso-video
  RESOURCE_GROUP: mslearn-gh-pipelines-5163
  NAMESPACE: index-app-ns
  IMAGE_NAME: index-app
  HELM_RELEASE_NAME: index-app
  HELM_CHART_PATH: ./helm-charts/index-app
  APP_VERSION: 1.0.0-${{ github.sha }}
  HELM_CHART_VERSION: 1.0-${{ github.sha }}
  ENV_FILE: env-config-var.yml

jobs:
  # CD Workflow
  deploy:
    runs-on: ubuntu-latest
    steps:
# ----------------------

    - name: "Checkout service repository"
      uses: actions/checkout@v3
      with:
        path: main

    - name: "Checkout services-helm-charts repository"
      uses: actions/checkout@v3
      with:
        repository: mehmetca-tr/services-helm-charts
        path: services-helm-charts

    - name: Import environment variables from the configuration variables maps file
      id: import-env
      shell: bash
      run: |
        while read line; do
          echo "$line" >> $GITHUB_ENV
        done < main/${{ env.ENV_FILE }}

    - name: Use the env var
      id: step_two
      run: |
        echo "${{ env.DEMO }}"
# ----------------------