name: "Test-CD-Workflow"

on:
  # push:
  #  branches:
  #    - main

  workflow_dispatch:  

env:
  ENV_FILE: env-config-var.txt

jobs:
  # CD Workflow
  deploy:
    runs-on: ubuntu-latest
    steps:
# ----------------------

    - name: "Checkout service repository"
      uses: actions/checkout@v3
      with:
        path: main

    - name: "Checkout services-helm-charts repository"
      uses: actions/checkout@v3
      with:
        repository: mehmetca-tr/services-helm-charts
        path: services-helm-charts

    - name: Import environment variables from the configuration variables maps file
      id: import-env
      shell: bash
      run: |
        while read line; do
          echo "$line" >> $GITHUB_ENV
        done < main/${{ env.ENV_FILE }}

    - name: Use the env var
      id: step_two
      run: |
        echo "${{ env.CLUSTER_NAME }}"
# ----------------------